<?php
# V.0.1.8
include_once 'init.php';
$user = new autentica($aA1);
$user -> login_standard();

$q = "
UPDATE descriptors SET
DESCRIPTOR_IT = CONCAT(UPPER(LEFT(DESCRIPTOR_IT, 1)), LOWER(SUBSTRING(DESCRIPTOR_IT, 2))),
DESCRIPTOR_EN = CONCAT(UPPER(LEFT(DESCRIPTOR_IT, 1)), LOWER(SUBSTRING(DESCRIPTOR_IT, 2))),
DESCRIPTOR_HR = CONCAT(UPPER(LEFT(DESCRIPTOR_IT, 1)), LOWER(SUBSTRING(DESCRIPTOR_IT, 2))),
DESCRIPTOR_DE = CONCAT(UPPER(LEFT(DESCRIPTOR_IT, 1)), LOWER(SUBSTRING(DESCRIPTOR_IT, 2))),
DESCRIPTOR_SI = CONCAT(UPPER(LEFT(DESCRIPTOR_IT, 1)), LOWER(SUBSTRING(DESCRIPTOR_IT, 2)))
WHERE ID_DESCRIPTORS_CATEG <> '1'
";

include_once HEAD_AR;

print $q;
mysql_query($q);

include_once FOOTER_AR;
?>